version: '3'

services:
  mysql:
    image: mysql
    ports:
      - '23306:3306'
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: ecommerceapp
      MYSQL_PASSWORD: mysql_native_password
      MYSQL_DATABASE: full-stack-ecommerce
    volumes:
    - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  spring-boot-ecommerce:
    image: artarkatesoft/fullstack-spring-boot-ecommerce
    restart: always
    ports:
      - 8082:8080
    depends_on:
      - mysql

  angular-ecommerce:
    image: artarkatesoft/fullstack-angular-ecommerce
    restart: always
    environment:
      API_URL: http://localhost:8082
    ports:
      - 4080:80
    depends_on:
      - spring-boot-ecommerce

volumes:
  mysql-data:

