version: '3'

services:
  mysql:
    image: mysql
    ports:
      - '23306:3306'
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: ecommerceapp
      MYSQL_PASSWORD: mysql_native_password
      MYSQL_DATABASE: full-stack-ecommerce
    volumes:
    - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

#  redis:
#    container_name: redis
#    hostname: redis
#    image: redis:6.2
#    ports:
#      - 6379:6379

volumes:
  mysql-data:

