spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/full-stack-ecommerce
    username: ecommerceapp
    password: mysql_native_password
  jpa:
    hibernate:
      ddl-auto: validate
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
  autoconfigure:
    exclude: org.redisson.spring.starter.RedissonAutoConfiguration
logging:
  level:
    net.shyshkin: debug
app:
  cors:
    allowedOrigins: http://localhost:4200
#    allowedOrigins: http://localhost:4200,http://localhost:4080
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:23306/full-stack-ecommerce
  jpa:
    show-sql: true