spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/full-stack-ecommerce
    username: ecommerceapp
    password: mysql_native_password
  jpa:
    hibernate:
      ddl-auto: validate
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
  autoconfigure:
    exclude: org.redisson.spring.starter.RedissonAutoConfiguration

logging:
  level:
    net.shyshkin: debug
app:
  cors:
    allowedOrigins: http://localhost:4200,https://localhost:4200
#    allowedOrigins: http://localhost:4200,http://localhost:4080
okta:
  oauth2:
    client-id: 0oa1mseq1yGM10BbP5d7
    client-secret: ${OKTA_OAUTH2_CLIENT_SECRET:some_fake_secret}
    issuer: https://dev-83879807.okta.com/oauth2/default

#####
#
# HTTPS configuration
#
#####

server:
  port: 8443
  ssl:
    enabled: true               # Enable HTTPS support (only accept HTTPS requests)
    key-alias: art2code         # Alias that identifies the key in the key store
    key-store: classpath:art2code-keystore.p12  # Keystore location
    key-store-password: secret  # Keystore password
    key-store-type: PKCS12      # Keystore format

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:23306/full-stack-ecommerce
  jpa:
    show-sql: true

---
spring:
  config:
    activate:
      on-profile: qa
server:
  port: 9898
